// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://cksvyzpzpgppmewgbzvj.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImNrc3Z5enB6cGdwcG1ld2dienZqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg2MDU4NDEsImV4cCI6MjA1NDE4MTg0MX0.YNjA2gHXFPHk00-xk15zGSN9rLmV7UA97DCtsO4XX8U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);